echo backend: > config.yml
echo   name: git-gateway >> config.yml
echo   branch: master >> config.yml
echo. >> config.yml
echo media_folder: "images" >> config.yml
echo public_folder: "/images" >> config.yml
echo. >> config.yml
echo collections: >> config.yml
echo   - name: "products" >> config.yml
echo     label: "Products" >> config.yml
echo     folder: "_data" >> config.yml
echo     create: true >> config.yml
echo     slug: "{{slug}}" >> config.yml
echo     fields: >> config.yml
echo       - { label: "Name", name: "name", widget: "string" } >> config.yml
echo       - { label: "Price", name: "price", widget: "string", required: false } >> config.yml
echo       - { label: "Category", name: "category", widget: "select", options: ["ladies", "kids"] } >> config.yml
echo       - { label: "Image", name: "image", widget: "image" } >> config.yml
echo       - { label: "Description", name: "description", widget: "text", required: false } >> config.yml