backend: 
  name: github 
  repo: sreelal1155/lakshmi-fashions 
  branch: master 
 
media_folder: "images" 
public_folder: "/images" 
 
collections: 
  - name: "products" 
    label: "Products" 
    folder: "_data" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - { label: "Name", name: "name", widget: "string" } 
      - { label: "Price", name: "price", widget: "string", required: false } 
      - { label: "Category", name: "category", widget: "select", options: ["ladies", "kids"] } 
      - { label: "Image", name: "image", widget: "image" } 
      - { label: "Description", name: "description", widget: "text", required: false } 
